name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rspec:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Run the default task
      env:
        VKPONCHIK_GROUP: ${{ secrets.VKPONCHIK_GROUP }}
        VKPONCHIK_TOKEN: ${{ secrets.VKPONCHIK_TOKEN }}
      run: |
        gem install bundler -v 2.2.4
        bundle install
        bundle exec rake spec
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Run the rubocop task
      run: |
        gem install bundler -v 2.2.4
        bundle install
        bundle exec rake rubocop

